### ISSUE TITLE
How do you get data from a serialized document field?

### ISSUE THREAD

**Issue by oagix** [palkerecsenyi/firestore-serializers#3]
I used serializeQuerySnapshot to format the result of the snapshot, but every document reference gets stored as a regular string in the final object, like this: `__DocumentReference__occupations/ZG1jP4NzZtuXZA69XZeR`. How do you pull data from it and is there any way to render it as a regular object instead of a string?

@palkerecsenyi 

Thank you!

**Comment by oagix** [comment]
This is the collection item reference in Firestore:

<img width="579" alt="image" src="https://user-images.githubusercontent.com/8274669/89119069-e3325480-d49a-11ea-87ae-e3d4d4f7eda6.png">

And the function that's trying to map data:

<img width="496" alt="image" src="https://user-images.githubusercontent.com/8274669/89119088-fd6c3280-d49a-11ea-9fe6-0e238f77117a.png">

The final object renders like this instead of having the reference documents as objects:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/8274669/89119105-14128980-d49b-11ea-81a6-f30acaa4ecd8.png">

**Comment by palkerecsenyi** [comment]
Hi, thanks for your question! In Firebase, Document References don't actually store any data, but just refer to a document. To get the data of a Reference, you need to query it.

My package serialises Firestore document data just to the extent so that it can be reconstructed into the original JavaScript Firestore document snapshot. To serialise the actual data referenced by a Document Reference, you'll need to query the reference using `.get()`, and then serialise the Document Snapshot you get back instead of the reference.

Let me know if you need any more help.

**Comment by oagix** [comment]
Gotcha, thank you! So would that mean that for every profile load, we need to run 4 queries? Is there a way to combine them in one query like you'd do with GraphQL for example?

**Comment by oagix** [comment]
Sent an email @palkerecsenyi . Thanks!
